In [2]:
import numpy as np

In [1]:
import numpy as np

arr = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])

for x in np.nditer(arr):
  print(x)


1
2
3
4
5
6
7
8


In [2]:
import numpy as np

arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

for x in np.nditer(arr[:, ::2]):
  print(x)

1
3
5
7


In [3]:
import numpy as np

arr = np.array([1, 2, 3])

for idx, x in np.ndenumerate(arr):
  print(idx, x)

(0,) 1
(1,) 2
(2,) 3


In [5]:
arr=np.array([1,2,3,4,5]);
print(arr)


[1 2 3 4 5]


In [12]:
# 0D array
arr0d=np.array(23);
#1d array

arr1d=np.array([1,2,3,4,5]);
# 2d array

arr2d=np.array([[1,2],[3,4],[5,6]]);
# 3d array

arr3d=np.array([[[1,2,3],[11,12,13]],[[21,22,23,],[31,32,33]]]);
print(" 0D array");
print(arr0d)


print(" 1D array");
print(arr1d)


print(" 2D array");
print(arr2d)

print(" 0D array");
print(arr3d)

 0D array
23
 1D array
[1 2 3 4 5]
 2D array
[[1 2]
 [3 4]
 [5 6]]
 0D array
[[[ 1  2  3]
  [11 12 13]]

 [[21 22 23]
  [31 32 33]]]


In [13]:

a = np.array(42)
b = np.array([1, 2, 3, 4, 5])
c = np.array([[1, 2, 3], [4, 5, 6]])
d = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)

0
1
2
3


# print(arr3d[1,1,2]) #indexing
print(arr3d[0:2,1:2,0:0])


In [33]:
print(arr3d[0:2,1:2,0:0])

[]
