In [1]:
import numpy as np

In [10]:
arr=np.array([1,2,3,4,5])

In [11]:
np.sum(arr)

np.int64(15)

In [14]:
arr=np.array([23,34,45,67,78])
print(arr,arr.shape,arr.dtype);

[23 34 45 67 78] (5,) int64


In [16]:
arr=np.array([[2,3],[4,5],[6,7],[8,9]]);
print(arr)

[[2 3]
 [4 5]
 [6 7]
 [8 9]]


In [4]:
arr1=np.zeros((2,4),dtype="int64")
print(arr1,arr1.dtype);

[[0 0 0 0]
 [0 0 0 0]] int64


In [8]:
arr1=np.ones((5,4),dtype="int64")
print(arr1,arr1.dtype);

[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]] int64
